import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ReactFlow, Background, Controls, MiniMap, Handle, Position, type NodeProps } from '@xyflow/react';
import '@xyflow/react/dist/style.css'; import './styles.css';
import { toTopicForest, truncateContent, type ConversationNode, type WorkspaceResponse, type ForestNode } from './conversation-tree.js';
const api=(import.meta.env.VITE_API_URL||'http://localhost:3001').replace(/\/$/,'');
function Card({data}:NodeProps){const value=data as unknown as ForestNode['data'];if(value.topic){const t=value.topic;return <><Handle type="target" position={Position.Left}/><div className={`topic-card ${value.active?'active':''} ${value.ancestor?'ancestor':''} ${t.contextEnabled?'':'disabled'}`}><div className="node-head"><b>{t.parentTopicId?'Subtopic':'Root topic'}</b><span>{t.contextEnabled?'Included':'Excluded'}</span></div><strong>{t.title}</strong>{t.description&&<div className="preview">{truncateContent(t.description,80)}</div>}</div><Handle type="source" position={Position.Right}/></>};const n=value.node!;return <><Handle type="target" position={Position.Left}/><div className={`node-card ${value.active?'active':''} ${n.contextEnabled?'':'disabled'}`}><div className="node-head"><b>{n.role}</b><span>{n.status}</span></div><div className="preview">{truncateContent(n.content)}</div>{n.tokenCount!==null&&<small>{n.tokenCount} tokens</small>}</div><Handle type="source" position={Position.Right}/></>}
function Details({node,topic,topics,nodes}:{node?:ConversationNode;topic?:{title:string;description:string|null;parentTopicId:string|null;contextEnabled:boolean;archivedAt:string|null;id:string};topics:{parentTopicId:string|null}[];nodes:ConversationNode[]}){return <aside className="details"><h2>{topic?'Topic details':'Node details'}</h2>{topic?<><dl><dt>Title</dt><dd>{topic.title}</dd><dt>Description</dt><dd>{topic.description||'—'}</dd><dt>Context</dt><dd>{topic.contextEnabled?'Included':'Excluded'}</dd><dt>Parent</dt><dd>{topic.parentTopicId||'Root topic'}</dd><dt>Child topics</dt><dd>{topics.filter(t=>t.parentTopicId===topic.id).length}</dd><dt>Messages</dt><dd>{nodes.filter(n=>n.topicId===topic.id).length}</dd></dl><p className="muted">Future actions: new subtopic, include/exclude, archive.</p></>:node?<><dl><dt>Role</dt><dd>{node.role}</dd><dt>Status</dt><dd>{node.status}</dd><dt>Context</dt><dd>{node.contextEnabled?'Included':'Excluded'}</dd><dt>Tokens</dt><dd>{node.tokenCount??'Not available'}</dd><dt>ID</dt><dd className="mono">{node.id}</dd></dl><h3>Complete content</h3><pre>{node.content||'(empty)'}</pre>{node.errorMessage&&<p className="error">{node.errorMessage}</p>}</>:<p className="muted">Select a topic or message to inspect it.</p>}</aside>}
export function App(){const [conversations,setConversations]=useState<{id:string,title:string}[]>([]);const [conversationId,setConversationId]=useState(new URLSearchParams(location.search).get('conversation'));const [tree,setTree]=useState<WorkspaceResponse|null>(null);const [selectedTopic,setSelectedTopic]=useState<string|null>(null);const [selected,setSelected]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{fetch(`${api}/conversations`).then(r=>r.json()).then(setConversations).catch(()=>setError('Unable to reach the backend.')).finally(()=>setLoading(false))},[]);
useEffect(()=>{if(!conversationId){setTree(null);return}setLoading(true);fetch(`${api}/conversations/${conversationId}`).then(r=>{if(!r.ok)throw Error('Conversation could not be loaded.');return r.json()}).then((v:WorkspaceResponse)=>{setTree(v);setSelectedTopic(v.activeTopicId??v.topics[0]?.id??null);setSelected(null)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[conversationId]);
const graph=useMemo(()=>tree?toTopicForest(tree,selectedTopic,selected):{nodes:[],edges:[]},[tree,selectedTopic,selected]);const active=tree?.nodes.find(n=>n.id===selected);const activeTopic=tree?.topics.find(t=>t.id===selectedTopic);const choose=(id:string)=>{setConversationId(id);history.pushState({},'',`?conversation=${encodeURIComponent(id)}`)};
return <div className="shell"><aside className="sidebar"><div className="brand">ArborAI</div><p className="muted">Conversation workspaces</p><div className="conversation-list">{loading&&!conversations.length?<p className="muted">Loading…</p>:conversations.length?conversations.map(c=><button className={c.id===conversationId?'conversation selected':'conversation'} onClick={()=>choose(c.id)} key={c.id}>{c.title}</button>):<p className="muted">No conversations yet.</p>}</div></aside><main className="main"><header className="topbar"><h1>{conversations.find(c=>c.id===conversationId)?.title||'Graph workspace'}</h1><span className="connection">{error?'Backend disconnected':'Backend connected'}</span></header><section className="workspace">{error?<div className="state error">{error}</div>:loading?<div className="state">Loading workspace…</div>:!tree?<div className="state"><strong>Select a conversation</strong><span>Choose one from the sidebar.</span></div>:!tree.topics.length?<div className="state"><strong>Empty workspace</strong></div>:<ReactFlow nodes={graph.nodes} edges={graph.edges.map(e=>({...e,style:{stroke:e.active?'#55d6be':'#aab6c8',strokeWidth:e.active?3:1.5}}))} nodeTypes={{topicNode:Card,messageNode:Card}} onNodeClick={(_,n)=>n.type==='topicNode'?(setSelectedTopic(n.id.replace('topic:','')),setSelected(null)):(setSelected(n.id.replace('message:','')),setSelectedTopic(tree.nodes.find(m=>m.id===n.id.replace('message:',''))?.topicId??null))} fitView nodesDraggable={false} nodesConnectable={false}><Background color="#dce3ed" gap={24}/><Controls/><MiniMap nodeColor={n=>n.type==='topicNode'?'#b18be0':'#6c8ee8'}/></ReactFlow>}</section></main><Details node={active} topic={!active?activeTopic:undefined} topics={tree?.topics??[]} nodes={tree?.nodes??[]}/></div>}

createRoot(document.getElementById('root')!).render(<App />);
